### PR TITLE
Carbide Theme

### PR DESCRIPTION
**Pull request by notcarbide**
Hello,

This is a theme based on 'paper-p'. It has some features (navbar, font) from 'material', navbar 'hamburger' menu animation, updated js-cookie, and an svg packed with some social media icons from Jekyll's default [minima theme](https://github.com/jekyll/minima/blob/master/assets/minima-social-icons.svg) (Spotify one I've imported added for bonus). It was created with mobile users in mind  and includes theming for Android notification bar.

This is somewhat of a pruned version than the original version of what we use (stripped of branding), but in the spirit of openness and transparency, I thought I'd share. :)

### CODE REVIEW

**Comment by robiso** [comment]
Thank you for sharing! Approved!

I'll make a couple of changes to the theme files (autosize doesn't need to be included anymore) and additionally, all JS and CSS libraries should include the 384 integrity hash.

I will also convert the theme to work with the upcoming version of WonderCMS 3.0.0, which breaks backwards compatibility due to the huge code changes made by @NicolasCARPi.

@notcarbide, can you share your first and last name + your Twitter or website? We'll add it to the [WonderCMS contributors page](https://wondercms.com/special-contributors).

**Comment by robiso** [comment]
@notcarbide, I've updated the theme to have the correct SRI tags as can be seen here:
- https://github.com/robiso/wondercms-themes/blob/master/themes/carbide-2/theme.php
- removed the unecessary autosize JS library, as WonderCMS includes it by default

Also fixed both CSS files (default and night), so the theme now properly works with displaying the settings panel.
Changes can be inspected here:
- https://github.com/robiso/wondercms-themes/blob/master/themes/carbide-2/css/style-default.css
- https://github.com/robiso/wondercms-themes/blob/master/themes/carbide-2/css/style-night.css

You can apply these changes to your theme (if you're using it) for a better experience.

**Comment by robiso** [comment]
@notcarbide, just noticed (and removed) what seemed like a bit of a hidden link to GitHub (in the about section).

If we add this theme to the "Approved WonderCMS themes" page, you can be properly credited as others have been (if you check the page), but unfortunately not in a way that would be included in the actual theme.

Didn't quite understand why the SVG was invisible, so I've removed it.
Just finished converting this theme to work with the upcoming WCMS 3.0.0.

**Comment by notcarbide** [comment]
Appreciate it!
It was just as an example on how to use it. Feel free to use them and point them to the relevant WonderCMS url :)
Name is Luis Cruz and twitter.com/syntecn

**Comment by robiso** [comment]
I just removed the whole wrapper altogether. 👍 

You've been added to the https://www.wondercms.com/special-contributors page.
Thanks for sharing! 🏆

**Comment by notcarbide** [comment]
Right. Apologies if it seemed like the link was hidden. I forgot to mention it, just like the whole night mode thing too. I'm quite spastic in nature lol.
What would be the best method of documenting their usage?

**Comment by robiso** [comment]
No problem at all, I'm quite spastic myself. I'm quite grateful for the experienced devs helping out on this 10 year old WCMS journey! :)

You can create a ReadMe file and it can be included in the theme or just have a read me file in your repo and we can link it in the approved themes (https://www.wondercms.com/themes) under the theme "Copy link" section of the theme.

**Comment by NicolasCARPi** [comment]
@robiso 

>  https://www.wondercms.com/themes

This page should have a clickable thumbnailed screenshot of each theme, asking a user to go on the demo site and login as admin and select a theme is too combersome.

**Comment by robiso** [comment]
@NicolasCARPi, +1 and agreed.

This has been on my TO-DO for a long, long time. Will probably start/finish this tomorrow.

**Pull request merged**
